// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ProMises
List ProMises(arma::mat X, float k, arma::mat Q, arma::mat ref_ds, bool scaling, bool reflection, bool centered);
RcppExport SEXP _alignProMises_ProMises(SEXP XSEXP, SEXP kSEXP, SEXP QSEXP, SEXP ref_dsSEXP, SEXP scalingSEXP, SEXP reflectionSEXP, SEXP centeredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< float >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ref_ds(ref_dsSEXP);
    Rcpp::traits::input_parameter< bool >::type scaling(scalingSEXP);
    Rcpp::traits::input_parameter< bool >::type reflection(reflectionSEXP);
    Rcpp::traits::input_parameter< bool >::type centered(centeredSEXP);
    rcpp_result_gen = Rcpp::wrap(ProMises(X, k, Q, ref_ds, scaling, reflection, centered));
    return rcpp_result_gen;
END_RCPP
}
// svdC
List svdC(arma::mat X);
RcppExport SEXP _alignProMises_svdC(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(svdC(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alignProMises_ProMises", (DL_FUNC) &_alignProMises_ProMises, 7},
    {"_alignProMises_svdC", (DL_FUNC) &_alignProMises_svdC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_alignProMises(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
