# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProMises <- function(X, k, Q, ref_ds, scaling, reflection, centered) {
    .Call('_alignProMises_ProMises', PACKAGE = 'alignProMises', X, k, Q, ref_ds, scaling, reflection, centered)
}

svdC <- function(X) {
    .Call('_alignProMises_svdC', PACKAGE = 'alignProMises', X)
}

