# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vMFP <- function(X, k, Q, ref_ds, scaling, reflection) {
    .Call('_vMFPmodelR_vMFP', PACKAGE = 'vMFPmodelR', X, k, Q, ref_ds, scaling, reflection)
}

svdC <- function(X) {
    .Call('_vMFPmodelR_svdC', PACKAGE = 'vMFPmodelR', X)
}

